### ISSUE TITLE
Serverコンテナがexit状態となる

### ISSUE THREAD

**Issue by naorespawn** [naorespawn/PokemonBattleCalculator#37]
# 概要
Serverコンテナがexit状態となる
# 再現手順
`docker-compose up -d`
# 原因
* `rails s`が実行できていない　エラー吐いているはず
<img width="1354" alt="スクリーンショット 2020-10-22 17 24 29" src="https://user-images.githubusercontent.com/47107757/96860930-5ba72100-149e-11eb-8a0d-3fa13cb58010.png">

**Comment by naorespawn** [comment]
```
=> Booting Puma
server_1  | => Rails 6.0.3.4 application starting in development 
server_1  | => Run `rails server --help` for more startup options
server_1  | Exiting
server_1  | /usr/local/bundle/gems/sprockets-rails-3.2.2/lib/sprockets/railtie.rb:106:in `block in <class:Railtie>': Expected to find a manifest file in `app/assets/config/manifest.js` (Sprockets::Railtie::ManifestNeededError)
```
[[Rails6][sprockets4.0.0]Sprocketsを無効にするためにapp/assetsフォルダ以下を削除すると、Sprockets::Railtie::ManifestNeededErrorが出た - Qiita](https://qiita.com/sasakura_870/items/106484f88c857bd9563e)

app/assetsフォルダが存在しないことによるエラーだった

GraphQL導入予定の環境のため，削除されているようだ

**Comment by naorespawn** [comment]
[【Rails】Rails 6.0 x Docker x MySQLで環境構築 - Qiita](https://qiita.com/nsy_13/items/9fbc929f173984c30b5d)

1. `server/`のrailsファイルを削除
2. `docker-compose run server rails new . --force --no-deps --database=mysql --skip-test --webpacker `で再インストール

**Comment by naorespawn** [comment]
```
db_1      | 2020-10-23T11:21:59.402182Z 0 [ERROR] [MY-010457] [Server] --initialize specified but the data directory has files in it. Aborting.
db_1      | 2020-10-23T11:21:59.402231Z 0 [ERROR] [MY-013236] [Server] The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it.
db_1      | 2020-10-23T11:21:59.404396Z 0 [ERROR] [MY-010119] [Server] Aborting
```

`docker-compose.yml` 
```
  db:
  ---
    volumes:
      # - server_db:/var/lib/mysql/data
         - server_db:/var/lib/mysql
```
に変更 DBのエラーは解消

**Comment by naorespawn** [comment]
```
server_1  | /usr/local/bundle/gems/webpacker-4.3.0/lib/webpacker/configuration.rb:95:in `rescue in load': Webpacker configuration file not found /myapp/server/config/webpacker.yml. Please run rails webpacker:install Error: No such file or directory @ rb_sysopen - /myapp/server/config/webpacker.yml (RuntimeError)
```

1. Rails6.0からWebpackerが標準となった
2. WebpackerのGemは入っているがインストールされていない
3. Webpackerの導入に必要なパッケージマネージャーyarnが入っていないから
4. `/server/Dockerfile`にyarnのインストールを追記する必要がある



* [【Rails】Rails 6.0 x Docker x MySQLで環境構築 - Qiita](https://qiita.com/nsy_13/items/9fbc929f173984c30b5d)

**Comment by naorespawn** [comment]
* [Rails用のDockerイメージのサイズを小さくする | Qrunch（クランチ）](http://www.qrunch.net/@mas61018/entries/woTtnV6irzMwaXn5?ref=qrunch)
* [Rails6を動かすAlpineベースのDockerfileを作成する(AlpineLinuxとは何か) - 独学プログラマ](https://blog.cloud-acct.com/posts/u-rails-dockerfile/#arg-%E5%A4%89%E6%95%B0%E5%90%8D)

1. `curl-dev mariadb-connector-c`をDockerfileに追記
2. `docker-compose run server rails webpacker:install`でWebpackerをインストール

```
-> % docker-compose ps -a
              Name                            Command               State                 Ports              
-------------------------------------------------------------------------------------------------------------
pokemonbattlecalculator_client_1   docker-entrypoint.sh npm r ...   Up      0.0.0.0:4020->3000/tcp           
pokemonbattlecalculator_db_1       docker-entrypoint.sh --def ...   Up      0.0.0.0:5432->3306/tcp, 33060/tcp
pokemonbattlecalculator_server_1   bundle exec rails server - ...   Up      0.0.0.0:3020->3000/tcp   
```

解決した

**Comment by naorespawn** [comment]
https://github.com/naorespawn/PokemonBattleCalculator/commit/462c2e7dd49cd6799b12abea896fecac84dafdadにてClose
